import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { canOpenExam, readCompletedSets, readRemembered } from '../lib/study-progress';
import { type Curriculum } from '../lib/curriculum';

export function ModeHub({ kind }: { kind: 'games' | 'exams' }) {
  const [data, setData] = useState<Curriculum | null>(null);
  const [selected, setSelected] = useState(['S01']);
  useEffect(() => { void import('../../data/curriculum.json').then(({ default: loaded }) => setData(loaded)); }, []);
  if (!data) return <main><h1>กำลังเปิด…</h1></main>;
  const remembered = readRemembered();
  const selectedSets = data.sets.filter((set) => selected.includes(set.id));
  const removeSet = (id: string) => setSelected((current) => current.filter((value) => value !== id));
  const toggleSet = (id: string) => setSelected((current) => current.includes(id) ? current.filter((value) => value !== id) : [...current, id]);
  if (kind === 'exams') { const passed = new Set(readCompletedSets()); return <main className="mode-hub"><p className="eyebrow">MASTERY EXAMS</p><h1>เลือกชุดข้อสอบ</h1><p>เลือกหมวดคำศัพท์ที่เรียนครบแล้วเพื่อเข้าสอบ</p><div className="set-grid">{data.sets.map((set) => { const isPassed = passed.has(set.id); return <Link key={set.id} to={`/exam/${set.id}`} className={`set-card exam-set-card ${isPassed ? 'passed' : ''}`}>{isPassed && <b className="passed-stamp">ผ่านแล้ว</b>}<header><b>SET {set.id.slice(1)}</b><small>{isPassed ? '✓ สอบผ่าน 100%' : canOpenExam(remembered, set.itemIds) ? '✓ พร้อมสอบ' : 'เรียนก่อน'}</small></header><strong>{set.category}</strong><footer><span>{set.itemIds.length} คำ</span><span>{isPassed ? 'ทำซ้ำ →' : 'เปิดข้อสอบ →'}</span></footer></Link>; })}</div></main>; }
  return <main className="mode-hub game-picker"><p className="eyebrow">GAME LIBRARY</p><h1>เลือกคำศัพท์สำหรับเกม</h1><p>แตะเซ็ตที่ต้องการได้เลย เลือกหลายเซ็ตเพื่อรวมคำศัพท์ในเกมเดียว</p><section className="game-presets"><b>เริ่มแบบเร็ว</b><div><button onClick={() => setSelected(['S01'])}>Set 01</button><button onClick={() => setSelected(['S01', 'S02'])}>S01 + S02</button><button onClick={() => setSelected(['S01', 'S02', 'S03'])}>S01 + S02 + S03</button></div></section><section className="selected-sets"><header><div><b>ชุดที่เลือก</b><small>{selected.length} เซ็ต · {selectedSets.reduce((total, set) => total + set.itemIds.length, 0)} คำ</small></div><button onClick={() => setSelected([])}>ล้างทั้งหมด</button></header><div className="selected-set-chips">{selectedSets.length ? selectedSets.map((set) => <button key={set.id} className="selected-set-chip" onClick={() => removeSet(set.id)} aria-label={`ลบ ${set.id}`}><b>{set.id}</b><span>{set.category}</span><i>×</i></button>) : <p className="no-selected-sets">ยังไม่เลือกเซ็ต</p>}</div>{selected.length ? <Link className="play-selected" to={`/practice/${selected.join('+')}`}>เริ่มเล่น {selected.length} เซ็ตที่เลือก <span>→</span></Link> : <button className="play-selected" disabled>เลือกอย่างน้อย 1 เซ็ตเพื่อเริ่มเกม</button>}</section><section className="set-picker"><header><h2>เลือกเพิ่ม</h2><small>แตะอีกครั้งเพื่อนำออก</small></header><div>{data.sets.map((set) => { const active = selected.includes(set.id); return <button key={set.id} aria-label={active ? `เอา ${set.id} ออก` : `เลือก ${set.id}`} className={active ? 'selected' : ''} onClick={() => toggleSet(set.id)}><b>{active ? '✓ ' : ''}{set.id}</b><span>{set.category}</span><small>20 คำ</small></button>; })}</div></section></main>;
}
