'use client';
import { useMemo,useState } from 'react';
import type { VocabularySet } from '@/app/lib/curriculum/types';
import type { ExamStage } from '@/app/lib/progress/types';
import { createExam,gradeStage } from '@/app/lib/exams/engine';
const labels:Record<ExamStage,string>={meaning:'ความหมาย · ไม่มีพินอิน',hanzi:'พิมพ์ตัวจีน',tones:'เสียงวรรณยุกต์'};
export function ExamClient({set,passedStages=[]}:{set:VocabularySet;passedStages?:ExamStage[]}){
  const[stage,setStage]=useState<ExamStage>('meaning');const[started,setStarted]=useState(false);const[attemptId,setAttemptId]=useState('');const[index,setIndex]=useState(0);const[answers,setAnswers]=useState<Record<string,string>>({});const[result,setResult]=useState<ReturnType<typeof gradeStage>|null>(null);
  const exam=useMemo(()=>createExam({stage,items:set.items,seed:71}),[stage,set.items]);const question=exam.questions[index];const item=set.items.find(i=>i.id===question.itemId)!;
  async function begin(){const response=await fetch('/api/exams/start',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({setId:set.id,stage})});if(!response.ok)return;const data=await response.json();setAttemptId(data.attemptId);setStarted(true)}
  async function answer(value:string){const next={...answers,[question.itemId]:value};setAnswers(next);if(index===19){const local=gradeStage(stage,set.items,next);const response=await fetch('/api/exams/submit',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({attemptId,answers:next})});setResult(response.ok?await response.json():local)}else setIndex(index+1)}
  function choose(next:ExamStage){setStage(next);setStarted(false);setAttemptId('');setIndex(0);setAnswers({});setResult(null)}
  if(result)return <section className="rounded-[2rem] border border-blue-100 bg-white p-6 text-center"><p className={`text-6xl font-bold ${result.passed?'text-emerald-600':'text-rose-600'}`}>{result.score}/20</p><h2 className="mt-3 text-2xl font-bold">{result.passed?'ผ่าน 100%':'ยังไม่ผ่าน ต้องได้ 100%'}</h2>{!result.passed&&<p className="mt-2 text-slate-500">ผิด {result.missedItemIds.length} คำ · ระบบจะแสดงคำที่ผิดหลังจบเท่านั้น</p>}<button onClick={()=>choose(stage)} className="mt-6 min-h-12 rounded-xl bg-blue-500 px-5 font-semibold">สอบด่านนี้ใหม่ทั้งหมด</button></section>;
  return <div><div className="grid grid-cols-3 gap-2">{(['meaning','hanzi','tones'] as ExamStage[]).map(s=><button key={s} onClick={()=>choose(s)} className={`min-h-14 rounded-xl border p-2 text-xs ${stage===s?'border-blue-400/50 bg-blue-500/20 text-blue-700':'border-blue-100 text-slate-500'}`}>{passedStages.includes(s)?'✓ ':''}{labels[s]}</button>)}</div>{!started?<section className="mt-5 rounded-[2rem] border border-blue-100 bg-white p-7 text-center"><h2 className="text-2xl font-bold">สอบ {labels[stage]}</h2><p className="mt-3 text-slate-500">20 ข้อ ต้องถูกทุกข้อ ระบบไม่เฉลยระหว่างสอบ</p><button onClick={begin} className="mt-6 min-h-12 rounded-xl bg-blue-500 px-6 font-semibold">เริ่มสอบ</button></section>:<section className="mt-5 rounded-[2rem] border border-blue-100 bg-white p-5 text-center"><div className="flex justify-between text-sm text-slate-500"><span>ข้อ {index+1}/20</span><span>{labels[stage]}</span></div><div className="mt-9 text-5xl font-semibold">{stage==='meaning'?question.prompt.hanzi:question.prompt.thai}</div>{stage==='meaning'?<div className="mt-8 grid grid-cols-2 gap-3">{question.choices!.map(choice=><button key={choice} onClick={()=>answer(choice)} className="min-h-14 rounded-xl border border-blue-100 bg-white p-3">{choice}</button>)}</div>:<form onSubmit={e=>{e.preventDefault();const form=new FormData(e.currentTarget);answer(String(form.get('answer')??''));e.currentTarget.reset()}} className="mt-8"><input name="answer" className="min-h-14 w-full rounded-xl border border-blue-200 bg-white px-4 text-center text-xl outline-none focus:border-blue-400" placeholder={stage==='tones'?`เลขโทน ${item.pinyin.split(/\s+/).length} พยางค์`:'พิมพ์ตัวจีน'}/><button className="mt-3 min-h-12 w-full rounded-xl bg-blue-500 font-semibold">ส่งคำตอบ</button></form>}</section>}</div>;
}
