import type { CardStudyInput, ExamResult, ExamStage, GameAttemptInput, SetProgress, SubmitExamInput } from './types';
export interface ProgressRepository { markCardStudied(input: CardStudyInput): Promise<void>; getSetProgress(userId: string, setId: string): Promise<SetProgress>; saveGameAttempt(input: GameAttemptInput): Promise<void>; submitExam(input: SubmitExamInput): Promise<ExamResult>; }
export class MemoryProgressRepository implements ProgressRepository {
  private cards = new Map<string, CardStudyInput>(); private receipts = new Set<string>(); private events = new Map<string, number>(); private passed = new Map<string, Set<ExamStage>>();
  async markCardStudied(input: CardStudyInput) { const receipt = `${input.userId}:${input.requestId}`; if (this.receipts.has(receipt)) return; this.receipts.add(receipt); this.cards.set(`${input.userId}:${input.itemId}`, input); const event = `${input.userId}:${input.itemId}`; this.events.set(event, (this.events.get(event) ?? 0) + 1); }
  async countCardEvents(userId: string, itemId: string) { return this.events.get(`${userId}:${itemId}`) ?? 0; }
  async getSetProgress(userId: string, setId: string): Promise<SetProgress> { const studiedCount = [...this.cards.values()].filter(card => card.userId === userId && card.setId === setId).length; const passedStages = [...(this.passed.get(`${userId}:${setId}`) ?? new Set<ExamStage>())]; return { setId, studiedCount, examUnlocked: studiedCount === 20, passedStages, completed: passedStages.length === 3 }; }
  async saveGameAttempt(_input: GameAttemptInput) {} async submitExam(_input: SubmitExamInput): Promise<ExamResult> { return { score: 0, total: 20, passed: false, missedItemIds: [] }; }
}
export class D1ProgressRepository implements ProgressRepository {
  constructor(private readonly db: D1Database) {}
  async markCardStudied(input: CardStudyInput) { const now = new Date().toISOString(); const prior = await this.db.prepare('SELECT 1 FROM mutation_receipts WHERE user_id=? AND request_id=?').bind(input.userId, input.requestId).first(); if (prior) return; await this.db.batch([this.db.prepare('INSERT INTO mutation_receipts(user_id,request_id,kind,created_at) VALUES(?,?,?,?)').bind(input.userId,input.requestId,'card',now),this.db.prepare('INSERT INTO user_word_progress(user_id,item_id,set_id,status,studied_at,updated_at) VALUES(?,?,?,?,?,?) ON CONFLICT(user_id,item_id) DO UPDATE SET status=excluded.status,updated_at=excluded.updated_at').bind(input.userId,input.itemId,input.setId,input.status,now,now)]); }
  async getSetProgress(userId: string, setId: string): Promise<SetProgress> { const count = await this.db.prepare('SELECT COUNT(*) AS total FROM user_word_progress WHERE user_id=? AND set_id=?').bind(userId,setId).first<{total:number}>(); const row = await this.db.prepare('SELECT meaning_passed_at,hanzi_passed_at,tones_passed_at,completed_at FROM user_set_progress WHERE user_id=? AND set_id=?').bind(userId,setId).first<Record<string,string|null>>(); const passedStages: ExamStage[] = []; if (row?.meaning_passed_at) passedStages.push('meaning'); if (row?.hanzi_passed_at) passedStages.push('hanzi'); if (row?.tones_passed_at) passedStages.push('tones'); const studiedCount = Number(count?.total ?? 0); return { setId, studiedCount, examUnlocked: studiedCount === 20, passedStages, completed: Boolean(row?.completed_at) }; }
  async saveGameAttempt(input: GameAttemptInput) { await this.db.prepare('INSERT OR IGNORE INTO game_attempts(id,user_id,set_id,mode,score,missed_item_ids,created_at) VALUES(?,?,?,?,?,?,?)').bind(input.id,input.userId,input.setId,input.mode,input.score,JSON.stringify(input.missedItemIds),new Date().toISOString()).run(); }
  async submitExam(_input: SubmitExamInput): Promise<ExamResult> { throw new Error('Use the exam submission service'); }
}
